### ISSUE TITLE
Excel export fail

### ISSUE THREAD

**Issue by sixy6e** [ausseabed/qax#28]
QAX fails to export the results of a _density check_ to Excel.

**Comment by sixy6e** [comment]
Traceback:

 
```python
 ERROR     root.export_qajson_excel:184 > Traceback (most recent call last):
  File "hyo2\qax\lib\project.py", line 177, in export_qajson_excel
    exporter.export(
  File "hyo2\qax\lib\qajson_util.py", line 395, in export
    tableSummary.build()
  File "hyo2\qax\lib\qajson_util.py", line 266, in build
    value = self._get_field_value(field.name, section.name, filename)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "hyo2\qax\lib\qajson_util.py", line 254, in _get_field_value
    value = plugin.get_summary_value(section_name, field_name, filename, self.qajson)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ausseabed\mbesgc\qax\plugin.py", line 253, in get_summary_value
AttributeError: 'NoneType' object has no attribute 'outputs'
```

**Comment by sixy6e** [comment]
Resolved by https://github.com/ausseabed/mbes-grid-checks/pull/4
